version: '3.8'

services:
  db:
    build:
      context: . 
      dockerfile: db.Dockerfile 
    container_name: marketplace_db_container
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}  
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketplace_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: marketplace_app_container
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "host=db user=postgres password=${DB_PASSWORD} dbname=${DB_NAME} port=5432 sslmode=disable TimeZone=Europe/Moscow"
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: