version: '3.8'

services:
  db:
    build:
      context: . 
      dockerfile: db.Dockerfile 
    container_name: marketplace_db_container
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: marketplace_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketplace_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: marketplace_app_container
    restart: always
    ports:
      - "8080:8080"
    environment: {}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: